# -*- coding: utf-8 -*-
"""apply 함수를 활용하여 DataFrame 가공_class101_데이터 마이닝.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18l7wparyYJpenIHEFc7YQhBLS6U4w1t9

# apply() : 내가 만든 함수를 데이터 프레임에 적용
"""

def my_func1(x):
    return x ** 2

def my_func2(x, n):
    return x ** n

my_func1(4)

my_func2(2, 5)

import pandas as pd

df = pd.DataFrame({
    'a' : [10, 20, 30],
    'b' : [20, 30, 40]
})

df

df['a']

df['a'] ** 2

df['a'].apply(my_func1)

df['a'].apply(my_func2, n=3)

def my_print(x):
    print()

df.apply(my_print, axis = 0)    # default axis=0 // 행방향 //axis=1 // 열방향

df

df.apply(my_print, axis = 1)

def my_avg(col):
    a = 0
    for i in col:
        a += i
    return a / len(df)

df.apply(my_avg, axis = 1)

