# -*- coding: utf-8 -*-
"""Grouping and  Sorting_Kaggle micro courses_Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11uGcOQAtJgbWND-p2EmXUlRNmcKP5tje

# Groupwise analysis
"""

import pandas as pd
reviews = pd.read_csv("winemag-data-130k-v2.csv")
pd.set_option('display.max_rows', 5)

reviews.groupby('points').points.count()

reviews.groupby('points').price.min()

reviews.groupby('winery').apply(lambda df: df.title.iloc[0])

reviews.head(20)

reviews.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.idxmax()])

reviews.groupby(['country']).price.agg([len, min, max])

"""# Multi-indexes"""

countries_reviewed = reviews.groupby(['country', 'province']).description.agg([len])
countries_reviewed
# when outputting the result of a groupby, the order of the rows is dependent on the values in the index, not in the data.

mi = countries_reviewed.index
type(mi)

# Most often is the one for converting back to a regular index
countries_reviewed.reset_index()

"""# Sorting"""

countries_reviewed = countries_reviewed.reset_index()
countries_reviewed.sort_values(by='len')

countries_reviewed.sort_values(by='len', ascending=False)

countries_reviewed.sort_index()

countries_reviewed.sort_values(by=['country', 'len'])

