# -*- coding: utf-8 -*-
"""groupby()함수를 이용해 데이터를 집단화하여 통계값 확인하기_class101_데이터 마이닝.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JjZJ9ch8VdUYJZsGgqbRWJGc7RsSv0N3

# groupby()함수 사용하기
"""

import pandas as pd

df = pd.read_csv("gapminder.tsv", sep='\t')
df

result = df.groupby('year')['lifeExp'].mean()
result

result.plot()

result2 = df.groupby(['year', 'continent'])['lifeExp'].mean()
result2

df.groupby('continent')['country'].nunique()    # nunique(): 중복 없이 고유한 값만 세기
                                                # count(): 중복을 포함하여 세기

"""# agg()함수를 결합해 groupby()함수와 같이 사용하기
agg(): 커스텀 함수 적용
"""

def my_func(x):
    n = len(x)
    dsum = 0
    for i in x:
        dsum += i
    return dsum / n

df.groupby('year')['lifeExp'].agg(my_func)    # agg(): groupby함수와 결합하여 사용, apply()함수처럼 만든 함수를 적용

