# -*- coding: utf-8 -*-
"""pandas 자료형 변환_class101_데이터 마이닝.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xhu2acRHwemKujOj_4ZYZr6xodGPg8ql
"""

import pandas as pd
import seaborn as sns

tips = sns.load_dataset('tips')
tips

tips.info()

# object: 문자열, 용량 차지 많음
# category: 범주형 문자열, 용량 차지 적음

tips['sex_str'] = tips['sex'].astype(str)    # 자료형 변환
tips

tips.info()

tips['sex_str'] = tips['sex_str'].astype('category')
tips.info()

tips.loc[[1, 3, 5, 7], 'total_bill'] = 'missing'
tips

tips.info()    # 문자가 하나라도 들어가면 object 자료형

tips['total_bill'] = pd.to_numeric(tips['total_bill'], errors = 'coerce', downcast = 'float')    # coerce(억압): 문자 데이터는 결측치 처리
                                                                                                 # downcast='float': 낮은 메모리로 변환
tips

tips.info()

