# -*- coding: utf-8 -*-
"""Seaborn을 활용한 가시화_class101_데이터 마이닝.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xS1xS_YhL7ftEH4c_3V0RAAy5oQAlucJ
"""

import seaborn as sns

tips = sns.load_dataset("tips")
tips

tips['total_bill'].plot.hist()

tips[['total_bill', 'tip']].plot.hist(bins = 20, alpha = 0.5)

tips['tip'].plot.kde()

tips.plot.scatter(x = 'total_bill', y = 'tip')

tips.plot.hexbin(x = 'total_bill', y = 'tip')

tips.plot.hexbin(x = 'total_bill', y = 'tip', gridsize = 10)

tips.plot.box()    # 숫자로 이루어진 셀들을 자동으로 표현

tips.info()    # float, int...

tips[['total_bill', 'tip']].plot.box()

"""# 다른 데이터프레임을 불러와서 판다스를 활용해서 그래프를 그려보고 인증하기"""

sns.get_dataset_names()

seaice = sns.load_dataset('seaice')
seaice

seaice['Extent'].plot.hist(bins = 40)

