# -*- coding: utf-8 -*-
"""seaborn 라이브러리를 활용한 가시화_class101_데이터 마이닝.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WvxAiCPdmOOdD5Ig4FgiTIg8eACjaXYt
"""

import seaborn as sns

tips = sns.load_dataset('tips')

sns.histplot(tips['total_bill'], bins = 30)    # 일변량 혹은 단변량 그래프

sns.kdeplot(tips['total_bill'])

sns.countplot('day', data = tips)

# 이변량
sns.lmplot(x = 'total_bill', y = 'tip', data = tips)    # 회귀선을 지우고 싶으면 매개변수에 fit_reg = False 추가

sns.jointplot(x = 'total_bill', y = 'tip', data = tips)

sns.lmplot(x = 'total_bill', y = 'tip', data = tips, hue = 'sex')    # 3가지 항목 표현

sns.jointplot(x = 'total_bill', y = 'tip', data = tips, kind = 'hex')

sns.barplot(x = 'time', y = 'total_bill', data = tips)    # 평균 막대 그래프
                                                          # 검은 선은 신뢰구간

sns.boxplot(x = 'time', y = 'total_bill', data = tips)

sns.set_style("whitegrid")
sns.violinplot(x = 'time', y = 'total_bill', data = tips, hue = 'sex')

sns.pairplot(tips)

anscombe = sns.load_dataset('anscombe')
anscombe

sns.lmplot(x = 'x',
           y = 'y',
           data = anscombe,
           col = "dataset",  # col="dataset": dataset별로 따로 그림을 그려줘
           col_wrap = 2)     # col_wrap=2: 2열까지만 그려줘

import matplotlib.pyplot as plt

facet = sns.FacetGrid(tips, col = 'time',   # 그룹별로 그래프
                      hue = 'sex',          # 다변량 그래프
                      row = 'smoker')    
facet.map(plt.scatter, 'total_bill', 'tip')
facet.add_legend()                          # 범례

"""# 다른 데이터 프레임을 가져와서 seaborn 라이브러리를 사용하여 그래프를 그리고 인증하기"""

sns.get_dataset_names()

dots = sns.load_dataset('dots')
dots

sns.boxplot(x = 'coherence', y = 'firing_rate', data = dots)

