# -*- coding: utf-8 -*-
"""같은 의미를 가진 열들을 하나의 열로 만들기_class101_데이터마이닝.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/128ruLPuOTjahq9h58StrkS-9yzBLsw8o
"""

import pandas as pd

pew = pd.read_csv('pew.csv')
pew

# pd.melt() 열에 있는 값을 행으로 내리는 함수
# 매개변수 id_vars에 행으로 내리지 않는 함수를 할당
# 새롭게 생긴 열의 이름과 값을 가진 열의 이름을 할당
pew2 = pd.melt(pew, id_vars = 'religion', var_name = 'income', value_name = 'count')
pew2.head(20)

ebola = pd.read_csv('country_timeseries.csv')
ebola

ebola2 = pd.melt(ebola, id_vars = ['Date', 'Day'], var_name = 'variable', value_name = 'count')
ebola2

ebola_split = ebola2['variable'].str.split('_')
ebola_split

state = ebola_split.str[0]
state

country = ebola_split.str[1]
country

ebola2['State'] = state
ebola2['Country'] = country
ebola2

del ebola2['variable']
ebola2

