# -*- coding: utf-8 -*-
"""결측치를 처리하는 다양한 방법_class101_데이터 마이닝.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HorBL7nFrBDHhu0TqmA7aj9OoSiR89RM

# 결측치는 비교할 수 없다
"""

from numpy import NaN, NAN, nan

5 ==  5

nan == nan    # 결측치는 일반적인 방법으로 비교할 수 없다
              # 무조건 False

import pandas as pd

pd.isnull(nan)    # 결측치 확인 함수

"""# 결측치 개수 구하기"""

ebola = pd.read_csv('country_timeseries.csv')
ebola

122 - ebola.count()    # 행 개수 - df.count()

sum(122 - ebola.count())    # 결측치 총 개수

"""# 결측치 채우기"""

# 결측치를 채우지 않으면 연산 불가능

ebola.fillna(0)    # 결측치를 0으로 채움

ebola.fillna(5)    # 결측치를 5로 채움

ebola.mean()

ebola.fillna(ebola.mean())    # 각 열의 평균값으로 채움

# 시계열 데이터에서 결측치를 평균으로 채우면 오차가 큼

# 결측치 앞의 값
ebola.fillna(method = 'ffill')    # front fill

# 결측치 뒤의 값
ebola.fillna(method = 'bfill')    # back fill

ebola.interpolate()    # 흐름에 맞게 결측치 채움

times = ['12/1/2016', '12/3/2016', '12/4/2016', '12/10/2016']

dates = pd.to_datetime(times, format = '%m/%d/%Y')
dates

ts = pd.Series([1, nan, nan, 10], index=dates)
ts

ts.interpolate()

ts.interpolate(method = 'time')

# 결측치가 하나라도 있는 행은 지움

ebola.dropna()

ebola.drop(121)

# 특정 조건을 만족하는 행을 지움

idx = ebola[ebola['Day'] > 100].index
idx

ebola.drop(idx)

