# -*- coding: utf-8 -*-
"""데이터프레임 다루기_class101_데이터마이닝.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Idac0ovG11vD_z-EEONc5UzB0ypz2PNo

# 데이터 프레임 다루기

# 데이터 프레임 불러오기

### csv : 콤마(,)를 기준으로 데이터를 구분함
### tsv : 탭(Tab)을 기준으로 데이터를 구분함
"""

import pandas as pd

df = pd.read_csv("gapminder.tsv", sep = '\t')    # "gapminder.tsv"파일을 가져온 후 'Tab'키를 기준으로 구분 (\t = Tab)
df

"""# 열에 접근하기"""

df['country']

df[['country', 'year']]    # 2개 이상의 columns를 불러올 경우 []로 한번 더 묶어준다

"""# 행에 접근하기"""

df.loc[0]                                           # 0이라고 적힌 행 가져오기

df.iloc[0]                                          # 0번째 행 가져오기

df.loc[[0, 10, 100, 1000], ['country', 'year']]     # 0, 10, 100, 1000이라고 적힌 행과 country, year이라고 적힌 열 가져오기

df.iloc[[0, 10, 100, 1000], [0, 2]]                 # 0, 10, 100, 1000번째 행과 0, 2번째 열 가져오기

"""# 원하는 행만 추출하기"""

df[(df['year'] == 1952) & (df['continent'] == 'Asia')]    # A & B : 둘 다 충족 시 추출, A | B : A와 B중 하나만 충족해도 추출

"""# 데이터 프레임 기본 기능"""

df.head()

df.head(n = 10)

df.tail()

df.tail(n = 7)

df.shape

df.columns

df.dtypes    # object는 문자열 int64는 64비트로 이루어진 정수형

df.info()    # 모든 열이 1704개의 행을 가지므로 결측치 없음, 만약 행의 갯수가 다르면 결측치가 있다고 판단

"""# gapminder.tsv 파일을 판다스를 통해 데이터프레임으로 가져오고, 출생년도가 1957년도인 행만 추출하고 인증하기"""

import pandas as pd

df = pd.read_csv("gapminder.tsv", sep = "\t")

df[df['year'] == 1957]

