# -*- coding: utf-8 -*-
"""스마트하게 데이터프레임 합치는 방법_class101_데이터 마이닝.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1GrpRCQDnTSq1PoIahtiFscmCWshVnx
"""

import pandas as pd

person = pd.read_csv('survey_person.csv')
site = pd.read_csv('survey_site.csv')
survey = pd.read_csv('survey_survey.csv')
visited = pd.read_csv('survey_visited.csv')

person

site

survey

visited

# df1.merge(df2, left_on="df1의 기준열",right_on="df2의 기준열")
# 각 데이터프레임의 기준열을 보고 열 방향으로 합침
# 기준열의 이름이 같다면 on="기준열"

result = visited.merge(site, left_on = 'site', right_on = 'name')
result

del result['name']
result

result2 = result[['ident', 'site', 'lat', 'long', 'dated']]
result2

"""# 1. person, survey 데이터 프레임 합쳐보기

"""

df = person.merge(survey, left_on = 'ident', right_on = 'person')
del df['ident']
df_result = df[['person', 'personal', 'family', 'quant', 'taken', 'reading']]
df_result

"""# 2. visited, survey 데이터 프레임 합쳐보기"""

df5 = visited.merge(survey, left_on = 'ident', right_on = 'taken')
del df5['taken']
df_result2 = df5[['ident', 'person', 'quant', 'site', 'reading', 'dated']]
df_result2

