# -*- coding: utf-8 -*-
"""시간 데이터 처리하기_class101_데이터마이닝.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14HSHKosJlz5EEU-E2m5ewyb5A5BK6BMs

# 시간 데이터 처리하기

### to_datetime 함수 소개
"""

import pandas as pd

df = pd.read_csv("person_info.csv", encoding = 'euc-kr')
df

df.info()     # 출생일과 사망일이 문자열?

df + df      # 출생일과 사망일을 숫자로 인식한다면 사망일 - 출생일 = 며칠 살았는지

df['출생일2'] = pd.to_datetime(df['출생일'], format = '%Y-%m-%d')    # 4자리 숫자 : Y, 2자리 숫자 : y
df['사망일2'] = pd.to_datetime(df['사망일'], format = '%Y-%m-%d')
df

df.info()       # 출생일과 사망일은 문자열, 출생일2와 사망일2는 날짜

df['Day'] = df['사망일2'] - df['출생일2']
df

df = df[['이름', '출생일2', '사망일2', 'Day', '나이', '직업']]
df

df.columns = ['이름', '출생날짜', '사망날짜', '생존일수', '나이', '직업']
df

df['출생날짜'].dt.year

df['출생날짜'].dt.month

df['출생날짜'].dt.day

