# -*- coding: utf-8 -*-
"""시리즈와 데이터프레임_class101_데이터마이닝.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ke3M2XTGWr2nXJtwiCa3mMyC_q7epVmq

# 시리즈와 데이터 프레임이란?

### 시리즈: 열
### 데이터프레임: 표

# 시리즈 만들기
"""

import pandas as pd                                               # 판다스를 가져와서 'pd'라는 이름으로 사용하겠다

a = pd.Series([1, 3, 5, 4, 2], index = ['A', 'B', 'C', 'D', 'E']) # index 설정해서 열 이름 바꾸기
a

"""# 데이터 프레임 만들기"""

df = pd.DataFrame({
    "이름" : ['장원영', '강동원', '아이유'],
    "성별" : ['여자', '남자', '여자'],
    "나이" : [19, 40, 32]
}, index = ['가', '나', '다'], columns = ['나이', '이름', '성별'])                   # 매개변수 index, columns 포함
                                                                                     # index: 데이터프레임의 행 이름
df

"""# 시리즈 다루기"""

a = pd.Series([1, 3, 5, 4, 2, 1, 3, 5, 4, 2])
a

a + a    # 행 이름을 기준으로 연산

a * 2

a * a    # series의 데이터가 문자열일 시 에러

b = pd.Series([100, 100])
b

a + b    # 같은 행끼리 수행하고 그 외에는 NaN

a[a > a.mean()]

a > a.mean()    # bool값 반환

"""# 시리즈와 데이터프레임을 만들어보고 인증하기"""

myseries = pd.Series(['a', 1, 'b', 2], index = ['가', '나', '다', '라'])
myseries

myDF = pd.DataFrame({
    1 : ['apple', 'grape', 'lemon', 'banana'],
    'a' : ['사과', '포도', '레몬', '바나나'],
    2 : ['dog', 'cat', 'puppy', 'kitten'],
    'b' : ['개', '고양이', '강아지', '고양이']
}, index = ['가', '나', '다', '라'], columns = [1, 2, 'a', 'b'])
myDF

