# -*- coding: utf-8 -*-
"""여러 데이터 프레임을 합치는 방법_class101_데이터마이닝.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZLebOv8an-xk-deoiWYmD2xiGBjRZx-d

# 여러 데이터 프레임 합치기
concat() 함수: 여러 데이터 프레임을 열 이름 기준 또은 행 이름 기준으로 합쳐주는 함수
"""

import pandas as pd

df1 = pd.read_csv('concat_1.csv')
df2 = pd.read_csv('concat_2.csv')
df3 = pd.read_csv('concat_3.csv')

df1

df2

df3

result = pd.concat([df1, df2, df3])
result

# 열을 기준으로 합치기
result = pd.concat([df1, df2, df3], ignore_index = True)    # index 0부터 다시 조정
result

# 행을 기준으로 합치기
result2 = pd.concat([df1, df2, df3], axis = 1)    # (default) axis = 0
result2

result2 = pd.concat([df1, df2, df3], axis = 1, ignore_index = True)  
result2

df2.columns = ['A', 'C', 'E', 'F']
df2

pd.concat([df1, df2, df3])

df2.index = ['가', '나', '다', '라']
df2

pd.concat([df1, df2, df3], axis = 1)

