# -*- coding: utf-8 -*-
"""중복 데이터 처리_class101_데이터마이닝.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VJq9sAfwbqiBVsRyMfyATKxUbSA1oOX6
"""

import pandas as pd

billboard = pd.read_csv('billboard.csv')
billboard

billboard2 = pd.melt(billboard, 
                     id_vars = ['year', 'artist', 'track', 'time', 'date.entered'],
                     var_name = 'week',
                     value_name = 'rating')
billboard2

billboard3 = billboard2[['year', 'artist', 'track', 'time']]
billboard3

billboard3[billboard3['track'] == 'Loser']

billboard3.drop_duplicates()    # 고유한 행 하나를 남기고 나머지 행을 모두 삭제
                                # Series, DataFrame, Index 객체에 적용 가능

billboard4 = billboard3.drop_duplicates()
billboard4[billboard4['track'] == 'Loser']

billboard['wk1'].drop_duplicates()

