# -*- coding: utf-8 -*-
"""행의 값을 열로 변경하는 방법_class101_데이터마이닝.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XRc2RWBVgP90ahnzfxkUkSQeKsOYm513
"""

import pandas as pd

weather = pd.read_csv('weather.csv')
weather

weather2 = pd.melt(weather, 
                   id_vars = ['id', 'year', 'month', 'element'],
                   var_name = 'day',
                   value_name = 'temp')
weather2

# melt(): 열을 행으로 변경
# pivot_table(): 행을 열로 변경

weather3 = weather2.pivot_table(index = ['id', 'year', 'month', 'day'],   # 고정할 열 값
                                columns = 'element',                      # 열로 변경할 열
                                values = 'temp',                          # 열로 변경한 열들이 가지는 값
                                dropna = False)                           # 결측치 제거 여부
weather3

weather3.reset_index()    # 인덱스 값 초기화

